### ISSUE TITLE
pylinkedin.exceptions.ServerIpBlacklisted

### ISSUE THREAD

**Issue by Sreenuvasuluzinnov** [ericfourrier/scrape-linkedin#2]
By Using This we got an exception Like This

"pylinkedin.exceptions.ServerIpBlacklisted: Linkedin forbids certain type of cloud provider to do raw https requests line Aws, Digital Ocean"

**Comment by ericfourrier** [comment]
Unfortunately linkedin seems to ban http get requests from any ip now not only cloud providers ip blocks.

You can try to simulate a browser with selenium
