### ISSUE TITLE
Make filename compatible with Windows?

### ISSUE THREAD

**Issue by neilalex** [ericfourrier/scrape-linkedin#6]
Hi Eric,

I'm excited to try your package! 

I'm having trouble installing it or cloning it, though, I think because in the data directory there's a file named "&lt;div class="wrapper hp-nus-wrapper"&gt;.txt". This is creating an issue for me on Windows, since characters like < and > aren't supported in filenames... git and pip both just die. Is this filename critical or any chance it could be tweaked slightly?

Thank you again for this package!

Neil

**Comment by AlcherBlack** [comment]
+1

**Comment by ericfourrier** [comment]
Should be fixed ! Thanks for the feedback. Tell me if it is working now on Windows

**Comment by neilalex** [comment]
That seemed to fix it for me. Thank you!
